---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rhel9
    image: registry.access.redhat.com/ubi9/ubi-init
    pre_build_image: true
  - name: rhel8
    image: registry.access.redhat.com/ubi8/ubi-init
    tmpfs:
      - /run
      - /tmp
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
  - name: rhel7
    image: registry.access.redhat.com/ubi7/ubi-init
    pre_build_image: true
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: True
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .