---
- name: Restart node_exporter
  listen: "restart node_exporter"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"  
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
  when:
    - not ansible_check_mode
