---
- name: "Create dirs"
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.file:
    path: "{{ directory }}"
    owner: "{{ USER | default(ansible_user_id) or default(omit) }}"
    group: "{{ GROUP | default(omit) }}"
    mode: "{{ MODE | default(omit) }}"
    state: directory
  loop: "{{ DIRS | default(['/tmp/temp']) }}"
  loop_control:
    loop_var: directory
