---
- name: Enable docker commands without sudo
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.user:
    user: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Set user docker config
  ansible.builtin.lineinfile:
    line: export DOCKER_CONFIG="${DOCKER_CONFIG:-$HOME/.docker}"
    path: .bashrc

- name: Download docker compose
  ansible.builtin.uri:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    owner: "{{ ansible_user }}"
    group: docker
    mode: "0775"
    status_code: [200, 304]

- name: Copy docker compose to user folder
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.copy:
    src: /usr/local/lib/docker/cli-plugins/docker-compose
    dest: .docker/cli-plugins/docker-compose
    remote_src: true
...
