---
# tasks file for install_packages
- name: Update cache for ubuntu
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install packages from the CentOS repo
  ansible.builtin.package:
      name: "{{ package }}"
      state: present
  loop: "{{ PACKAGE_LIST }}"
  loop_control:
    loop_var: package
  notify: Start nginx

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
