---
name: "Test WP"
on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:

  ansible_check_hm:
    name: Run Ansible playbook
    runs-on: ubuntu-latest
    environment: FINAL_PROJECT
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Init terraform
        run: |
          cd TERRAFORM &&
          terraform init
      - name: Run hm playbook on check_mode
        uses: dawidd6/action-ansible-playbook@v2.8.0
        with:
          playbook: playbooks/health_monitor.yml
          directory: ./ANSIBLE/
          # Optional, SSH private key
          key: ${{secrets.SSH_KEY}}
          # known_hosts: |
          #   example.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          # Optional, encrypted vault password
          vault_password: ${{secrets.ANSIBLE_VAULT_PASSWORD}}
          # Optional, galaxy requirements filepath
          requirements: requirements.yml
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --inventory inventory/
            -vv
            -C
...
